
export const BENGALI_MONTHS = [
  'জানুয়ারি', 'ফেব্রুয়ারি', 'মার্চ', 'এপ্রিল', 'মে', 'জুন',
  'জুলই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'
];

export const ENGLISH_MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

export const CATEGORY_ICONS: { [key: string]: string } = {
  'বেতন': 'fa-money-check-dollar',
  'Salary': 'fa-money-check-dollar',
  'ব্যবসা': 'fa-briefcase',
  'Business': 'fa-briefcase',
  'কাস্টমার পেমেন্ট': 'fa-user-tag',
  'Customer Payment': 'fa-user-tag',
  'খাবার': 'fa-bowl-food',
  'Food': 'fa-bowl-food',
  'যাতায়াত': 'fa-bus',
  'Transport': 'fa-bus',
  'ভাড়া': 'fa-house-chimney',
  'Rent': 'fa-house-chimney',
  'দোকান': 'fa-shop',
  'Shop': 'fa-shop',
  'চিকিৎসা': 'fa-hand-holding-medical',
  'Medical': 'fa-hand-holding-medical',
  'অন্যান্য': 'fa-ellipsis',
  'Others': 'fa-ellipsis'
};

export const CATEGORIES = {
  income: {
    bn: ['বেতন', 'ব্যবসা', 'কাস্টমার পেমেন্ট', 'অন্যান্য'],
    en: ['Salary', 'Business', 'Customer Payment', 'Others']
  },
  expense: {
    bn: ['খাবার', 'যাতায়াত', 'ভাড়া', 'দোকান', 'চিকিৎসা', 'অন্যান্য'],
    en: ['Food', 'Transport', 'Rent', 'Shop', 'Medical', 'Others']
  }
};

export const I18N = {
  bn: {
    appName: 'ট্যালি খাতা',
    dashboard: 'হোম',
    transactions: 'লেনদেন',
    reports: 'রিপোর্ট',
    settings: 'সেটিংস',
    baki: 'বাকি খাতা',
    todayIncome: 'আজকের আয়',
    todayExpense: 'আজকের খরচ',
    balance: 'বর্তমান ব্যালেন্স',
    receivable: 'মোট পাওনা',
    payable: 'মোট দেনা',
    addTransaction: 'লেনদেন যোগ করুন',
    income: 'আয় (পেলেন)',
    expense: 'ব্যয় (দিলেন)',
    cash: 'নগদ',
    credit: 'বাকি',
    amount: 'টাকার পরিমাণ',
    category: 'ক্যাটাগরি',
    date: 'তারিখ',
    source: 'বিবরণ / নাম',
    note: 'নোট (ঐচ্ছিক)',
    save: 'সেভ করুন',
    cancel: 'বাতিল',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    confirmDelete: 'আপনি কি নিশ্চিত যে আপনি এই লেনদেনটি মুছতে চান?',
    noTransactions: 'কোন লেনদেন পাওয়া যায়নি',
    monthlySummary: 'মাসিক সারাংশ',
    totalIncome: 'মোট আয়',
    totalExpense: 'মোট খরচ',
    profit: 'লাভ',
    loss: 'ক্ষতি',
    monthlyNotes: 'মাসিক নোট',
    export: 'এক্সপোর্ট',
    reset: 'রিসেট ডাটা',
    resetWarning: 'সব ডাটা মুছে যাবে। আপনি কি নিশ্চিত?',
    language: 'ভাষা',
    searchPlaceholder: 'খুঁজুন...',
    currency: '৳',
    addPerson: 'নতুন কাস্টমার/সাপ্লায়ার',
    personName: 'নাম',
    personPhone: 'ফোন নম্বর',
    customer: 'কাস্টমার',
    supplier: 'সাপ্লায়ার',
    personList: 'ব্যক্তিদের তালিকা',
    noPeople: 'কেউ তালিকায় নেই',
    devProfile: 'ডেভলপার পরিচিতি',
    close: 'বন্ধ করুন',
    viewProfile: 'প্রোফাইল দেখুন',
    enterPin: 'পিন নম্বর দিন',
    wrongPin: 'ভুল পিন, আবার চেষ্টা করুন',
    budget: 'বাজেট',
    setBudget: 'বাজেট সেট করুন',
    remindWhatsApp: 'রিমাইন্ডার পাঠান',
    aiEntry: 'AI দিয়ে এন্ট্রি',
    dueDate: 'টাকা পাওয়ার তারিখ',
    overdue: 'সময় পার হয়ে গেছে',
    whatsappMessage: (name: string, amount: number) => `হ্যালো ${name}, আমার ট্যালি খাতায় আপনার বর্তমান ব্যালেন্স ৳${amount}। দয়া করে সময় করে চেক করবেন। ধন্যবাদ।`
  },
  en: {
    appName: 'Tally Khata',
    dashboard: 'Home',
    transactions: 'History',
    reports: 'Reports',
    settings: 'Settings',
    baki: 'Credit Book',
    todayIncome: "Today's Income",
    todayExpense: "Today's Expense",
    balance: 'Current Balance',
    receivable: 'Total Receivable',
    payable: 'Total Payable',
    addTransaction: 'Add Transaction',
    income: 'Income (Received)',
    expense: 'Expense (Paid)',
    cash: 'Cash',
    credit: 'Baki',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    source: 'Source / Name',
    note: 'Note (Optional)',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: 'Are you sure you want to delete this transaction?',
    noTransactions: 'No transactions found',
    monthlySummary: 'Monthly Summary',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    profit: 'Profit',
    loss: 'Loss',
    monthlyNotes: 'Monthly Notes',
    export: 'Export',
    reset: 'Reset Data',
    resetWarning: 'All data will be lost. Are you sure?',
    language: 'Language',
    searchPlaceholder: 'Search...',
    currency: '৳',
    addPerson: 'New Customer/Supplier',
    personName: 'Name',
    personPhone: 'Phone Number',
    customer: 'Customer',
    supplier: 'Supplier',
    personList: 'People List',
    noPeople: 'No one in list',
    devProfile: 'Developer Profile',
    close: 'Close',
    viewProfile: 'View Profile',
    enterPin: 'Enter PIN',
    wrongPin: 'Wrong PIN, try again',
    budget: 'Budget',
    setBudget: 'Set Budget',
    remindWhatsApp: 'Send Reminder',
    aiEntry: 'AI Quick Entry',
    dueDate: 'Due Date',
    overdue: 'Overdue',
    whatsappMessage: (name: string, amount: number) => `Hello ${name}, your current balance in my Tally Khata is ৳${amount}. Please check when you have a moment. Thank you.`
  }
};
